name: CLI CI

on:
  push:
    branches:
    - master
    - future
  pull_request:
    paths:
    - 'lib/python/**'
    - 'bin/qmk'
    - 'requirements.txt'
    - '.github/workflows/cli.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    # container: qmkfm/base_container
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    # - name: Install dependencies
    #   run: pip3 install -r requirements.txt
    - name: Test Dactyl
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        util/docker_build.sh handwired/dactyl_manuform/4x5:ChristofferNissen
