name: CLI CI

on:
  push:
    branches:
    - master
    paths:
    - keyboards/handwired/dactyl_manuform/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Test Dactyl
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        util/docker_build.sh handwired/dactyl_manuform/4x5:ChristofferNissen
